
POST http://localhost:8090/api/document/save
Content-Type: application/json

{
    "FormName":"Welcome",
    "Formelements":[
        {   
        "componentType": "input",
        "desc": {
            
            "index": 1,
            "type": "text", 
            "label": "Enter Your Name",
            "name": "Username",
            "placeholder": "",
            "width": 100,
            "value": "",
            "required":true
            
            }

    }
    
    
    ]
}
 
###


###
GET http://localhost:8090/api/document/get

